### ISSUE TITLE
на пк модлоадер не модлоадит

### ISSUE THREAD

**Issue by GDenisC** [BoolkaSDK/Loader#2]
Моды в папке есть но не работает

**Comment by cafeed28** [comment]
а в какой папке установлена гд и как файл мода называется?

**Comment by GDenisC** [comment]
kfg скачай там также

**Comment by cafeed28** [comment]
агде скачать

**Comment by GDenisC** [comment]
дс серв

**Comment by cafeed28** [comment]
го
![image](https://user-images.githubusercontent.com/62172116/157884485-fcf100dc-c7fa-490e-a354-5edfed1a0e60.png)
